#!/bin/bash
cd `dirname $1`
~/scripts/svg2pdf.sh
~/sync/proj/dllup/dlluptex.py < "`basename $1`.dllu" > "index_dllu.tex"
if [ ! -f "`basename $1`.tex" ]
then
    cp ~/sync/proj/dllup/texheader.tex "`basename $1`.tex"
fi
pdflatex "`basename $1`.tex" && pdflatex "`basename $1`.tex"
